apiVersion: 1
datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    url: http://prometheus:9090
    access: proxy
    isDefault: true
  - name: Jaeger
    uid: jaeger
    type: jaeger
    url: http://jaeger:16686
    access: proxy
