import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';
type Row=Record<string,any>;
const tabs=['Overview','Transactions','Experiments','Telemetry','Recovery','Reports'];
const presets:Record<string,string>={inventory_unavailable:'inventory',payment_latency:'payments',redis_outage:'redis',rabbitmq_interruption:'rabbitmq',worker_restart:'worker',postgres_interruption:'postgres'};
async function api(path:string,body?:unknown,headers?:Record<string,string>){const r=await fetch('/api'+path,{method:body===undefined?'GET':'POST',headers:{'Content-Type':'application/json',...headers},body:body===undefined?undefined:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw Error(data.error||`HTTP ${r.status}`);return data;}
function App(){
 const [tab,setTab]=useState('Overview'),[data,setData]=useState<Record<string,any>>({}),[error,setError]=useState(''),[busy,setBusy]=useState(false),[connected,setConnected]=useState(false),[loading,setLoading]=useState(true),[result,setResult]=useState<Row|null>(null);
 const [product,setProduct]=useState('mouse'),[quantity,setQuantity]=useState(1),[decline,setDecline]=useState(false),[key,setKey]=useState<string>(crypto.randomUUID()),[fault,setFault]=useState('inventory_unavailable'),[duration,setDuration]=useState(10),[baseline,setBaseline]=useState(15),[recovery,setRecovery]=useState(15),[magnitude,setMagnitude]=useState(1500),[stopRate,setStopRate]=useState(1),[profile,setProfile]=useState('baseline');
 async function refresh(){const paths=tab==='Transactions'?['/products','/orders']:tab==='Recovery'?['/control/recovery']:tab==='Reports'?['/control/reports']:tab==='Experiments'?['/control/experiments','/control/load']:['/control/services','/control/metrics','/control/experiments'];try{const rows=await Promise.all(paths.map(async p=>[p,await api(p)]));setData(Object.fromEntries(rows));setError('');}catch(e){setData({});setError(String(e));}finally{setLoading(false);}}
 useEffect(()=>{setResult(null);setLoading(true);void refresh();const t=setInterval(()=>void refresh(),5000);return()=>clearInterval(t)},[tab]);
 useEffect(()=>{const stream=new EventSource('/api/control/events');stream.addEventListener('connected',()=>setConnected(true));stream.addEventListener('update',()=>setConnected(true));stream.onerror=()=>setConnected(false);return()=>stream.close()},[]);
 async function command(path:string,body:unknown={},headers?:Record<string,string>){setBusy(true);setError('');try{setResult(await api(path,body,headers));await refresh();}catch(e){setError(String(e));}finally{setBusy(false)}}
 async function inspect(path:string){setBusy(true);try{setResult(await api(path));}catch(e){setError(String(e));}finally{setBusy(false)}}
 const experiments:Row[]=data['/control/experiments']||[],orders:Row[]=data['/orders']||[],services:Row[]=data['/control/services']||[],metrics:Row=data['/control/metrics']||{};
 function comparison(record:Row){const phases=(record.evidence||[]).filter((r:Row)=>r.phase);if(!phases.length)return null;return <table className="w-full text-sm my-3"><thead><tr><th>Phase</th>{["throughput","error_rate","completion_rate","p95","queue_backlog","retry_count"].map(k=><th key={k}>{k.replaceAll("_"," ")}</th>)}</tr></thead><tbody>{phases.map((p:Row)=><tr key={p.phase}><th>{p.phase}</th>{["throughput","error_rate","completion_rate","p95","queue_backlog","retry_count"].map(k=><td key={k}>{p[k]?.available?Number(p[k].value).toFixed(3):"Unavailable"}</td>)}</tr>)}</tbody></table>}
 function metricCards(){return <div className="grid grid-cols-2 md:grid-cols-4 gap-3">{Object.entries(metrics).filter(([,v])=>v&&typeof v==='object'&&'available'in v).map(([k,v])=><div className="bg-white p-3 rounded border" key={k}><div className="text-sm text-slate-600">{k.replaceAll('_',' ')}</div><div className="text-xl">{v.available?Number(v.value).toFixed(3):'Unavailable'}</div><details className="text-xs"><summary>Evidence</summary><pre>{JSON.stringify(v,null,2)}</pre></details></div>)}</div>}
 return <main className="max-w-7xl mx-auto p-6 space-y-5"><header className="flex justify-between gap-4"><div><h1 className="text-2xl font-semibold">Distributed Reliability Platform</h1><p className="text-slate-600">Local transaction system · controlled failures · measured recovery</p></div><span className={connected?'text-green-700':'text-amber-700'}>{connected?'Live events connected':'Live events disconnected'}</span></header>
 <nav className="flex flex-wrap gap-2">{tabs.map(t=><button key={t} onClick={()=>setTab(t)} className={t===tab?'bg-blue-700':''}>{t}</button>)}</nav>
 {error&&<div role="alert" className="p-3 bg-red-100 text-red-900">{error} <button onClick={()=>void refresh()}>Retry</button></div>}{loading&&<p>Loading operational data…</p>}
 {tab==='Overview'&&<><div className="grid grid-cols-3 gap-3">{services.map(s=><div className="bg-white border p-3 rounded" key={s.name}>{s.name}<p className={s.ready?'text-green-700':'text-red-700'}>{s.ready?'Ready':'Unavailable'}</p>{s.error&&<p className="text-xs">{s.error}</p>}</div>)}</div>{!services.length&&!loading&&<p>Service status unavailable.</p>}{metricCards()}<h2 className="text-lg">Current experiments</h2>{experiments.filter(e=>!['COMPLETED','FAILED','ABORTED'].includes(e.state)).map(e=><p key={e.id}>{e.spec.fault}: {e.state}</p>)}{experiments.every(e=>['COMPLETED','FAILED','ABORTED'].includes(e.state))&&<p>No active experiment.</p>}</>}
 {tab==='Transactions'&&<><h2 className="text-lg">Product inventory</h2><table className="w-full bg-white"><thead><tr><th>Product</th><th>Price (cents)</th><th>Available stock</th></tr></thead><tbody>{(data['/products']||[]).map((p:Row)=><tr key={p.id}><td>{p.name}</td><td>{p.price}</td><td>{p.stock}</td></tr>)}</tbody></table><form className="flex flex-wrap gap-3 items-end" onSubmit={e=>{e.preventDefault();void command('/orders',{product,quantity,decline},{'Idempotency-Key':key})}}><label>Product<select value={product} onChange={e=>setProduct(e.target.value)}>{(data['/products']||[]).map((p:Row)=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Quantity<input type="number" min="1" max="100" value={quantity} onChange={e=>setQuantity(Number(e.target.value))}/></label><label>Idempotency key<input value={key} onChange={e=>setKey(e.target.value)}/></label><label>Deterministic decline<input type="checkbox" checked={decline} onChange={e=>setDecline(e.target.checked)}/></label><button disabled={busy}>Submit transaction</button><button type="button" onClick={()=>setKey(crypto.randomUUID())}>New key</button></form><table className="w-full bg-white"><thead><tr><th>Order</th><th>State</th><th>Reason</th><th>Inspect</th></tr></thead><tbody>{orders.map(o=><tr key={o.id}><td className="text-xs">{o.id}</td><td>{o.state}</td><td>{o.reason}</td><td><button onClick={()=>void inspect('/transactions/'+o.id)}>Details</button> <a href={'http://localhost:16686/trace/'+o.trace_id} target="_blank" rel="noreferrer">Trace</a></td></tr>)}</tbody></table>{!orders.length&&!loading&&<p>No orders found.</p>}</>}
 {tab==='Experiments'&&<><form className="flex flex-wrap gap-3 items-end" onSubmit={e=>{e.preventDefault();void command('/control/experiments',{fault,target:presets[fault],magnitude,duration,baseline,recovery,stop_error_rate:stopRate})}}><label>Fault<select value={fault} onChange={e=>setFault(e.target.value)}>{Object.keys(presets).map(f=><option key={f}>{f}</option>)}</select></label>{[['Fault seconds',duration,setDuration,5],['Baseline seconds',baseline,setBaseline,10],['Recovery seconds',recovery,setRecovery,10],['Latency milliseconds',magnitude,setMagnitude,0]].map(([name,value,setter,min])=><label key={String(name)}>{String(name)}<input type="number" min={Number(min)} max={name==='Latency milliseconds'?3000:120} value={Number(value)} onChange={e=>(setter as (v:number)=>void)(Number(e.target.value))}/></label>)}<label>Stop error rate<input type="number" min="0.01" max="1" step="0.01" value={stopRate} onChange={e=>setStopRate(Number(e.target.value))}/></label><button disabled={busy}>Run measured experiment</button></form><p>Each run starts a small sustained k6 load, measures baseline, injects the fault, removes it, and verifies business consistency.</p><div className="flex gap-2"><select value={profile} onChange={e=>setProfile(e.target.value)}>{['baseline','concurrent','sustained','burst','recovery'].map(p=><option key={p}>{p}</option>)}</select><button disabled={busy} onClick={()=>void command('/control/load/start',{profile})}>Start load</button><button disabled={busy} onClick={()=>void command('/control/load/stop')}>Stop load</button></div><h2 className="text-lg">Load history</h2>{(data["/control/load"]||[]).map((l:Row)=><p key={l.id}>{l.profile} · {l.state} · {l.started_at}</p>)}{experiments.map(e=><div key={e.id} className="bg-white p-3 border flex gap-3 flex-wrap"><span>{e.spec.fault} · {e.state} · {e.error}</span><button onClick={()=>void inspect('/control/experiments/'+e.id)}>Evidence</button>{!['COMPLETED','FAILED','ABORTED'].includes(e.state)&&<><button onClick={()=>void command('/control/experiments/'+e.id+'/stop')}>Stop</button><button onClick={()=>void command('/control/experiments/'+e.id+'/recover')}>Recover</button></>}</div>)}</>}
 {tab==='Telemetry'&&<><div className="flex gap-4"><a href="http://localhost:3000/d/reliability" target="_blank" rel="noreferrer">Grafana dashboards</a><a href="http://localhost:16686" target="_blank" rel="noreferrer">Jaeger traces</a><a href="http://localhost:9090" target="_blank" rel="noreferrer">Prometheus queries</a></div><p>Measured rolling 30 second window. Missing or insufficient samples remain unavailable.</p>{metricCards()}</>}
 {tab==='Recovery'&&<><p>Backup the active PostgreSQL database; restore into an isolated recovery database and verify the exported snapshot watermark. RabbitMQ is outside this backup scope.</p><div className="flex gap-3"><button disabled={busy} onClick={()=>void command('/control/recovery/backup')}>Create backup</button><button disabled={busy} onClick={()=>void command('/control/recovery/verify')}>Restore and verify</button></div>{(data['/control/recovery']||[]).map((r:Row,i:number)=><details key={i} className="bg-white p-3"><summary>{r.action} · {new Date((r.timestamp||r.verified_at)*1000).toLocaleString()} {r.objective_met===undefined?'':r.objective_met?' · Objective met':' · Objective not met'}</summary><pre>{JSON.stringify(r,null,2)}</pre></details>)}</>}
 {tab==='Reports'&&<>{(data['/control/reports']||[]).map((r:Row)=><div key={r.id} className="bg-white border p-3 flex gap-4 flex-wrap"><span>{r.spec.fault} · {r.state} · {r.created_at}</span><button onClick={()=>void inspect('/control/reports/'+r.id)}>Inspect comparison</button><a href={'/api/control/reports/'+r.id}>Download JSON</a><a href={'/api/control/reports/'+r.id+'?format=html'} target="_blank" rel="noreferrer">Readable report</a></div>)}{!(data['/control/reports']||[]).length&&!loading&&<p>No completed experiment reports.</p>}</>}
 {result&&<section className="bg-white border rounded p-4"><div className="flex justify-between"><h2 className="text-lg">Operation evidence</h2><button onClick={()=>setResult(null)}>Close</button></div>{comparison(result)}<details open={!result.evidence}><summary>Raw evidence</summary><pre className="text-sm mt-3">{JSON.stringify(result,null,2)}</pre></details></section>}
 </main>
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
